logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  oauth2:
    client:
      registered-redirect-uri: http://example.com
      client-id: oauth
      client-secret: oauth
      scope: all
      access-token-validity-seconds: 6000
      refresh-token-validity-seconds: 6000
      grant-type: authorization_code,password
      resource-ids: oauth2
    resource:
      id: oauth2
    authorization:
      # 允许使用 /oauth/check_token 端点
      check-token-access: isAuthenticated()